Musllinux (#383)
* Create musllinux wheels

* musl tag

* finish audithweel & naming

* ditch arch hack

* support qemu cpu adjustment

* Add patch for armv6l

* update action

* cleanup

* Add tests

* cleanups

* Add build pipeline

* Fix lint

* cleanup rc

* Fix hadolint

* fix CI test wheels

* using official hadolint

* Fix hadolint

* Fix lint

* second run

* Fake image build

* Fix build

* Fix build v2

* add extension

* Fix lookup

* Fix multiarch

* Fix build issues

* Fix deps

* Fix build

* Don't use wheel for make wheels

* Fix dockerfile

* Fix install builder

* Sign image

* revert & add cache

* fix action

* fix line end

* Fix nothing to install

* ditch argument

* Fix CI

* line handling

* Fix

* Fix patch

* second one

* Fix patch

* revert chicken-egg

* fix archs

* Update Dockerfile

Co-authored-by: Franck Nijhof <frenck@frenck.nl>

* Update .github/workflows/publish.yml

Co-authored-by: Franck Nijhof <frenck@frenck.nl>

Co-authored-by: Franck Nijhof <frenck@frenck.nl>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2,17 +2,20 @@ name: "Home Assistant wheels builder"
 description: "Builds and publishes python wheels"
 inputs:
   tag:
-    description: "The tag for the builder that should be used"
-    default: "dev"
+    description: "The musllinux tag for the builder that should be used"
+    required: true
+  abi:
+    description: "CPython ABI that is used"
+    required: true
   arch:
     description: "Build architecture"
     required: true
   apk:
     description: "apk packages that should be installed"
-    default: "build-base"
+    default: ""
   pip:
     description: "pip packages that should be installed"
-    default: "Cython"
+    default: ""
   path:
     description: "The path to be used for the builder"
     default: ""
@@ -46,9 +49,6 @@ inputs:
   skip-binary:
     description: "Skip binaries"
     default: ""
-  audit:
-    description: "Audit wheels"
-    default: false
   wheels-key:
     description: "SSH keys for the wheels host"
     required: false
@@ -66,6 +66,15 @@ runs:
   using: "composite"
   steps:
     - shell: bash
+      id: version
+      run: |
+        input=$(echo "${{ github.action_path }}" | cut -d"/" -f8 )
+        if [[ "${input}" == "master" ]] || [[ -z "${input}" ]]; then
+          input="dev"
+        fi
+        echo "::set-output name=version::${input}"
+
+    - shell: bash
       run: |
         if [[ "${{ inputs.test }}" =~ false|False ]]; then
           # Write Key
@@ -79,12 +88,25 @@ runs:
           chmod 600 .ssh/*
         fi
 
+    - uses: home-assistant/actions/helpers/cas@master
+
     - shell: bash
       id: pull
       run: |
-        name="homeassistant/${{ inputs.arch }}-base-python:${{ inputs.tag }}"
+        name="ghcr.io/home-assistant/wheels/${{ inputs.arch }}/${{ inputs.tag }}/${{ inputs.abi }}:${{ steps.version.outputs.version }}"
         docker pull "$name"
         echo "::set-output name=name::$name"
+
+    - shell: bash
+      run: |
+        for j in {1..15}; do
+          if CAS_API_KEY= cas authenticate --silent --signerID notary@home-assistant.io docker://${{ steps.pull.outputs.name }}; then
+            exit 0
+          fi
+          sleep $((5 * j))
+        done
+        echo "Invalid signature!"
+        exit 1
 
     - shell: bash
       id: options
@@ -115,7 +137,7 @@ runs:
         if [ -d "${{ inputs.prebuild-dir }}" ]; then
           build+=("--prebuild-dir ${{ github.workspace }}/${{ inputs.prebuild-dir }}")
         fi
-        if  [[ "${{ inputs.single }}" =~ true|True ]]; then
+        if [[ "${{ inputs.single }}" =~ true|True ]]; then
           build+=("--single")
         fi
         if [[ "${{ inputs.local }}" =~ true|True ]]; then
@@ -124,11 +146,19 @@ runs:
         if [[ "${{ inputs.test }}" =~ true|True ]]; then
           build+=("--test")
         fi
-        if [[ "${{ inputs.audit }}" =~ true|True ]]; then
-          build+=("--auditwheel")
-        fi
         if [ -n "${{ inputs.skip-binary }}" ]; then
-          build+=("--skip-binary ${{ inputs.skip-binary }}")
+          build+=("--skip-binary \"${{ inputs.skip-binary }}\"")
+        fi
+        if [ -n "${{ inputs.apk }}" ]; then
+          build+=("--apk \"${{ inputs.apk }}\"")
+        fi
+        if [ -n "${{ inputs.pip }}" ]; then
+          build+=("--pip \"${{ inputs.pip }}\"")
+        fi
+
+        # Qemu armv6 CPU fix
+        if [[ "${{ inputs.arch }}" == "armhf" ]]; then
+          docker+=("-e QEMU_CPU=arm1176")
         fi
 
         echo "::set-output name=build::${build[@]}"
@@ -141,26 +171,14 @@ runs:
 
     - shell: bash
       run: |
-        echo "Build image"
-        docker build ${{ github.action_path }} \
-          -t wheels-builder \
-          --build-arg BUILD_FROM=${{ steps.pull.outputs.name }} \
-          --build-arg BUILD_ARCH=${{ inputs.arch }}
-
-    - shell: bash
-      run: |
         echo "Create container"
         docker create --name "${{ inputs.name }}" -t \
           --workdir /data \
           ${{ steps.options.outputs.docker }} \
-          "wheels-builder" \
-          --apk "${{ inputs.apk }}" \
-          --pip "${{ inputs.pip }}" \
+          ${{ steps.pull.outputs.name }} \
           --index "${{ inputs.wheels-index }}" \
           --upload rsync \
           --remote "${{ inputs.wheels-user }}@${{ inputs.wheels-host }}:/opt/wheels" \
-          --arch "${{ inputs.arch }}" \
-          --tag "${{ inputs.tag }}" \
           ${{ steps.options.outputs.build }}
 
     - shell: bash
