Sign image

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -88,12 +88,25 @@ runs:
           chmod 600 .ssh/*
         fi
 
+    - uses: home-assistant/actions/helpers/cas@master
+
     - shell: bash
       id: pull
       run: |
         name="ghcr.io/home-assistant/wheels/${{ inputs.arch }}/${{ inputs.tag }}/${{ inputs.abi }}:${{ steps.version.outputs.version }}"
         docker pull "$name"
         echo "::set-output name=name::$name"
+
+    - shell: bash
+      run: |
+        for j in {1..15}; do
+          if CAS_API_KEY= cas authenticate --silent --signerID notary@home-assistant.io docker://${{ steps.pull.outputs.name }}; then
+            exit 0
+          fi
+          sleep $((5 * j))
+        done
+        echo "Invalid signature!"
+        exit 1
 
     - shell: bash
       id: options
